### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Stevengeilo** [forkpoweroutlet/genshin-pity-calculator#17]
I could need some help with the Installation cuz i'm too dump for it. I have Node installed but ye the rest confuses me kinda hard, idk how to do it. Would be nice if you can help me and if i try to use the Pity Calculator nothing happens, ig it's cuz of the Installation? Could you do a video or something to show how i have to do it?

**Comment by forkpoweroutlet** [comment]
Hi! If you want to just use the calculator tool, it's [available online as a webpage](https://git.io/pitycalc), zero installation required. In this case, I'll assume you're trying to build it on your machine.

The reason why the calculator isn't functioning is probably because the code was not yet bundled by Webpack. Check the README's Installation section, specifically the last two commands. You want to change your terminal's directory to the folder with this repository's content is located, and run `npm install` followed by `npm run build`.

How familiar with the command line are you, and how to use it?

**Comment by Stevengeilo** [comment]
I'm like zero familiar with that and don't know how to use it and that's my problem

**Comment by forkpoweroutlet** [comment]
What operating system are you using: Windows, Mac, or Linux?

**Comment by Stevengeilo** [comment]
Windows

**Comment by forkpoweroutlet** [comment]
Alright, you need to open the folder with the files when you use the commands. On Windows there exists a trick to open a folder with the terminal: just open the folder you want to open in file explorer and type `cmd` in the bar at the top:
![GIF](https://i.gyazo.com/3f020a8ddb27393aa344826f9641723e.gif)

From there, select the command prompt and type in `npm install`, press enter, and wait for that to finish.
Then type `npm run build`, enter, wait again. After the build finishes, it should be working if all goes well.

**Comment by Stevengeilo** [comment]
Works now, very big thank you <3.

**Comment by forkpoweroutlet** [comment]
No problem, glad I could help. :D
